#!/bin/sh

if [[ $UID -eq 0 ]]; then
   echo "Why would you install your dotfiles as root? Silly."
   exit 1;
fi

echo -n "Are you sure you want to install? This will overwrite your dotfiles in ~/. [yN] "
read __R
if [[ $__R != "y" ]]; then
    echo "Aborting..."
    exit 130;
fi

BASE=`basename $0`
if [[ ! -f "./$BASE" ]]; then
    echo "You must run this script from within the repository!"
    exit 1;
fi

echo ">> Updating submodules"
git submodule update --init --recursive

echo ">> Deploying dotfiles"
for FILE in $(ls -A); do
    if [[ $BASE == $FILE || $FILE == ".git"  || $FILE == ".gitmodules" ]]; then # Don't copy the installer or .git folder.
	continue
    fi

    if [[ -f "$HOME/$FILE" || -d "$HOME/$FILE" ]]; then
        echo "  +Update:  $FILE"
    else
        echo "  +Install: $FILE"
    fi
    cp -r -u "$FILE" ~/
done

echo ">> Done copying files. Post-install routine"
if [ -d ".ssh" ]; then
    echo "  +chmod: .ssh (700)"
    chmod 700 ~/.ssh
fi

echo ">> Done!"
