#!/bin/sh

if [[ -z "$LOCAL_BIN" ]]; then
   echo "\$LOCAL_BIN not set... defaulting to ~/.bin"
   LOCAL_BIN=~/.bin
fi

if [ ! -f "$LOCAL_BIN/TechnicLauncher.jar" ]; then
   echo "Error: Technic Launcher not found at $LOCAL_BIN/TechnicLauncher.jar"
   exit
fi

java -jar $LOCAL_BIN/TechnicLauncher.jar
