#!/bin/sh
# ---
alias rzshrc='source ~/.zshrc'
alias aliases='emacs ~/.zsh/aliases'
alias zshrc='emacs ~/.zsh/zshrc'
# ---
alias ls='ls --color=auto'
alias irc='ssh moria -t tmux a'
alias genetec='rdesktop -g 1920x1080 -P -z -u abeaulieu -d GENETEC -r sound:off localhost:3389'
# ---
alias twitch='chromium --app=https://www.twitch.tv/'
alias netflix='chromium --app=https://www.netflix.com/'
alias slack='chromium --app=https://slack.com'
