#!/bin/sh
# ---
alias rzshrc='source ~/.zshrc'
alias aliases='$EDITOR ~/.zsh/aliases'
alias zshrc='$EDITOR ~/.zsh/zshrc'
alias mux='tmuxinator'
# ---
alias ls='ls --color=auto'
alias irc='ssh segfault -t tmux a'
alias kali='ssh relay'
alias win64='rdesktop -g 1440x900 -P -z localhost'
# ---
alias twitch='chromium --app=https://www.twitch.tv/'
alias netflix='chromium --app=https://www.netflix.com/'
alias youtube='chromium --app=https://www.youtube.com'

