#!/usr/bin/zsh
ZSHCFG="$HOME/.zsh"
ZSH="$ZSHCFG/oh-my-zsh"
ZSH_CUSTOM="$ZSHCFG"
plugins=(archlinux docker compleat git github gpg-agent ssh-agent nvm tmux fzf workon)

setopt completealiases

_has() {
  return $(whence $1 >/dev/null)
}

# EXPORTS
#########################################################
if _has fzf && _has ag; then
  export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
  # export FZF_BASE=$(dirname $(which fzf))
  export FZF_CTRL_T_COMMAND="fd . 2>/dev/null"
  export FZF_ALT_C_COMMAND="fd -t d 2>/dev/null"
  export FZF_DEFAULT_OPTS='--height 30% --layout=reverse'
fi
##########################################################

# Disable annoying auto-correct.
if [[ -f $ZSHCFG/zsh_nocomp ]]; then
    while read -r COMMAND; do
        alias $COMMAND="nocorrect $COMMAND"
    done < "$ZSHCFG/zsh_nocomp"
fi



[[ -f $ZSHCFG/aliases ]] && source $ZSHCFG/aliases # Aliases.
[[ -f "$HOME/.xresources.d/dircolors" ]] && eval $(dircolors $HOME/.xresources.d/dircolors) # Colors.

DISABLE_AUTO_TITLE=true
if [ $EUID -eq 0 ]; then
   ZSH_DISABLE_COMPFIX="true"
fi
source "$ZSHCFG/zsh_theme"

# use nvim if available.
if command -v nvim &>/dev/null; then
    export EDITOR=nvim
    alias vim='nvim'
else
    export EDITOR=vim
fi

stty -ixon # stop C-Q, C-S from freezing terminal.

source "$ZSHCFG/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
