#!/usr/bin/zsh
ZSHCFG="$HOME/.zsh"
ZSH="$ZSHCFG/oh-my-zsh"
ZSH_CUSTOM="$ZSHCFG"


# Process overrides for a specific host.
if [[ -f "$HOME/.zsh/override/$HOST" ]]; then
    source "$HOME/.zsh/override/$HOST"
fi

plugins=(docker gpg-agent ssh-agent fzf workon navi zsh-syntax-highlighting zsh-histdb)

setopt completealiases

_has() {
  return $(whence $1 >/dev/null)
}

# EXPORTS
#########################################################
if _has fzf && _has rg; then
  export FZF_DEFAULT_COMMAND='rg --color never --files'
  export FZF_CTRL_T_COMMAND="rg --files . 2>/dev/null"
  export FZF_ALT_C_COMMAND="fd -t d 2>/dev/null"
  export FZF_DEFAULT_OPTS='--height 30% --layout=reverse'
fi
##########################################################

# Disable annoying/dangerous auto-correct.
if [[ -f $ZSHCFG/zsh_nocomp ]]; then
    while read -r COMMAND; do
        alias $COMMAND="nocorrect $COMMAND"
    done < "$ZSHCFG/zsh_nocomp"
fi


DISABLE_AUTO_TITLE=true
if [ $EUID -eq 0 ]; then
   ZSH_DISABLE_COMPFIX="true"
fi
source "$ZSHCFG/zsh_theme"

# Pick an editor.
local editors=(emacsclient nvim vim vi nano)
for e in $editors; do
    if _has $e; then
	export EDITOR=$e
	break
    fi
done 

# Pick a terminal.
local terms=(st termite)
for t in $terms; do
    if _has $t; then
	export TERMINAL=$t
	break
    fi
done 


stty -ixon # stop C-Q, C-S from freezing terminal.

# Source aliases last to make sure they don't get overwritten.
[[ -f $ZSHCFG/aliases ]] && source $ZSHCFG/aliases # Aliases.
[[ -f "$HOME/.xresources.d/dircolors" ]] && eval $(dircolors $HOME/.xresources.d/dircolors) # Colors.

export GHIDRA_INSTALL_DIR="$HOME/.bin/Ghidra/"
