#!/usr/bin/zsh
ZSHCFG="$HOME/.zsh"
ZSH="$ZSHCFG/oh-my-zsh"
ZSH_CUSTOM="$ZSHCFG" # For oh-my-zsh

plugins=(archlinux docker compleat git github ssh-agent gpg-agent nvm tmux)
GEOMETRY_PROMPT_PLUGINS=(virtualenv docker_machine exec_time git hg)
setopt completealiases

_has() {
  return $(whence $1 >/dev/null)
}

# Disable annoying auto-correct.
if [[ -f $ZSHCFG/zsh_nocomp ]]; then
    while read -r COMMAND; do
        alias $COMMAND="nocorrect $COMMAND"
    done < "$ZSHCFG/zsh_nocomp"
fi

# Load aliases
if [[ -f $ZSHCFG/aliases ]]; then
    source $ZSHCFG/aliases
fi


DISABLE_AUTO_TITLE=true
ZSH_THEME="geometry/geometry"

# oh-my-zsh
source "$ZSH/oh-my-zsh.sh"

# FZF && ag
if _has fzf && _has ag; then
  export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
fi

# Load up colors
if [[ -f "$HOME/.xresources.d/dircolors" ]]; then
    eval `dircolors $HOME/.xresources.d/dircolors`
fi

# PATH
export PATH=$PATH:~/.cargo/bin:~/.gem/ruby/2.5.0/bin
export DEV_PATH="$HOME/dev"
export PEDA="$DEV_PATH/foss/peda"

stty -ixon # stop C-Q, C-S from freezing terminal.

# use nvim if available.
if command -v nvim &>/dev/null; then
    export EDITOR=nvim
    alias vim='nvim'
else
    export EDITOR=vim
fi

export LANG="en_CA.UTF-8"
export LC_ALL="en_CA.UTF-8"

